import assert from 'node:assert/strict';
import test from 'node:test';

import {
	expandOccurrences,
	forecastBalances,
	rankSuggestedMatches,
	resolveOccurrence,
	type PlannedTransaction
} from './planning';

const plan = (overrides: Partial<PlannedTransaction> = {}): PlannedTransaction => ({
	id: 'plan',
	accountId: 'account',
	kind: 'expense',
	amountMinor: 100n,
	date: '2024-01-31',
	status: 'expected',
	exceptions: [],
	active: true,
	cancelled: false,
	...overrides
});

test('expands weekly intervals and respects an inclusive end date', () => {
	const dates = expandOccurrences(
		plan({
			date: '2026-01-01',
			recurrence: { frequency: 'weekly', interval: 2, endDate: '2026-02-01' }
		}),
		'2026-01-01',
		'2026-12-31'
	).map((x) => x.date);
	assert.deepEqual(dates, ['2026-01-01', '2026-01-15', '2026-01-29']);
});

test('monthly missing days use month-end and rebound to the anchor day', () => {
	assert.deepEqual(
		expandOccurrences(
			plan({ recurrence: { frequency: 'monthly', interval: 1 } }),
			'2024-01-01',
			'2024-04-30'
		).map((x) => x.date),
		['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30']
	);
});

test('yearly leap-day recurrence rebounds after a non-leap year', () => {
	assert.deepEqual(
		expandOccurrences(
			plan({ date: '2024-02-29', recurrence: { frequency: 'yearly', interval: 1 } }),
			'2024-01-01',
			'2028-12-31'
		).map((x) => x.date),
		['2024-02-29', '2025-02-28', '2026-02-28', '2027-02-28', '2028-02-29']
	);
});

test('exceptions change, skip and restore individual occurrences', () => {
	const occurrences = expandOccurrences(
		plan({
			recurrence: { frequency: 'monthly', interval: 1 },
			exceptions: [
				{ originalDate: '2024-02-29', action: 'change', date: '2024-03-02', amountMinor: 250n },
				{ originalDate: '2024-03-31', action: 'skip' },
				{ originalDate: '2024-04-30', action: 'restore' }
			]
		}),
		'2024-02-01',
		'2024-04-30'
	);
	assert.deepEqual(
		occurrences.map((x) => [x.originalDate, x.date, x.amountMinor]),
		[
			['2024-02-29', '2024-03-02', 250n],
			['2024-04-30', '2024-04-30', 100n]
		]
	);
});

test('occurrence identity remains the original generated date after rescheduling', () => {
	const changed = plan({
		recurrence: { frequency: 'monthly', interval: 1 },
		exceptions: [{ originalDate: '2024-02-29', action: 'change', date: '2024-03-02' }]
	});
	assert.equal(resolveOccurrence(changed, '2024-02-29')?.date, '2024-03-02');
	assert.equal(resolveOccurrence(changed, '2024-03-02'), undefined);
});

test('rejects exceptions whose original date is not generated by the rule', () => {
	assert.throws(
		() =>
			expandOccurrences(
				plan({
					recurrence: { frequency: 'monthly', interval: 1 },
					exceptions: [{ originalDate: '2024-02-28', action: 'skip' }]
				}),
				'2024-01-01',
				'2024-12-31'
			),
		/not generated/
	);
});

test('future exception remains valid after an earlier exclusive cutoff', () => {
	const stopped = plan({
		date: '2026-01-01',
		recurrence: { frequency: 'monthly', interval: 1 },
		cutoffDate: '2026-03-01',
		exceptions: [{ originalDate: '2026-05-01', action: 'skip' }]
	});
	assert.deepEqual(
		expandOccurrences(stopped, '2026-01-01', '2026-12-31').map((item) => item.originalDate),
		['2026-01-01', '2026-02-01']
	);
});

test('effective segments preserve the original month-end cadence', () => {
	assert.deepEqual(
		expandOccurrences(
			plan({
				date: '2024-01-31',
				effectiveFrom: '2024-02-29',
				recurrence: { frequency: 'monthly', interval: 1 }
			}),
			'2024-02-01',
			'2024-04-30'
		).map((occurrence) => occurrence.originalDate),
		['2024-02-29', '2024-03-31', '2024-04-30']
	);
});

test('forecast moves overdue expected plans to today and toggles tentative plans', () => {
	const plans = [
		plan({ id: 'old', date: '2026-01-01' }),
		plan({ id: 'maybe', date: '2026-09-01', kind: 'income', amountMinor: 40n, status: 'tentative' })
	];
	const account = [{ id: 'account', currentBalanceMinor: 1000n }];
	const expected = forecastBalances(account, plans, { today: '2026-08-06' });
	assert.equal(expected[0]?.currentBalanceMinor, 1000n);
	assert.equal(expected[0]?.endingBalanceMinor, 900n);
	assert.equal(expected[0]?.occurrences[0]?.date, '2026-08-06');
	assert.equal(
		forecastBalances(account, plans, { today: '2026-08-06', includeTentative: true })[0]
			?.endingBalanceMinor,
		940n
	);
});

test('match suggestions require account/kind/14-day window and rank equal amounts first', () => {
	const occurrence = {
		accountId: 'account',
		kind: 'expense' as const,
		amountMinor: 100n,
		date: '2026-08-15'
	};
	const ranked = rankSuggestedMatches(occurrence, [
		{ id: 'near', accountId: 'account', kind: 'expense', amountMinor: 99n, date: '2026-08-14' },
		{ id: 'equal', accountId: 'account', kind: 'expense', amountMinor: 100n, date: '2026-08-29' },
		{ id: 'far', accountId: 'account', kind: 'expense', amountMinor: 100n, date: '2026-08-30' },
		{ id: 'wrong', accountId: 'other', kind: 'expense', amountMinor: 100n, date: '2026-08-15' }
	]);
	assert.deepEqual(
		ranked.map((x) => x.transaction.id),
		['equal', 'near']
	);
	assert.ok(ranked.every((x) => x.autoConfirmed === false));
});
